title: Joshua Ajene
logo: Ajene.PNG
description: 
Data Analyst with 4 years experience working accros different sectors using advance excel for report automation, Sql for data manipulation and interogation and power Bi for creating business intelligence report.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
